CREATE TABLE IF NOT EXISTS projects(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    priority INTEGER NOT NULL,
    description TEXT,
    delivery_date date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    done BOOLEAN ,
    project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE
);

INSERT INTO projects(name, priority, description, delivery_date)
VALUES('CRA', 1, 'create-react-app', '2020-10-10');

INSERT INTO projects(name, priority, description, delivery_date)
VALUES('CVA', 1, 'create-vue-app', '2020-12-24');

INSERT INTO tasks(name, done, project_id)
VALUES('install something', true, 1);